Calcular medidas estatísticas básicas, como:  
Média;  
Mediana;  
Valor mínimo;  
Valor máximo;  
Criar pelo menos um gráfico, podendo ser:  
Histograma; ou Boxplot;

In [4]:
# Importando as bibliotecas necessárias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# Importando o arquivo CSV
dfsalario = pd.read_csv('C:/Users/robso/Documents/GitHub/SCTEC/Projeto_Final/CSV_01.csv')

In [8]:
# Visualizando as primeiras linhas do DataFrame
dfsalario.head()

     DEPARTAMENTO                          CARGO  SALARIO
0      Accounting             Accounting Manager    12008
1      Accounting              Public Accountant     8300
2  Administration       Administration Assistant     4400
3       Executive                      President    24000
4       Executive  Administration Vice President    17000

In [12]:
# Visualizando os tipos de dados das colunas
dfsalario.dtypes

DEPARTAMENTO      str
CARGO             str
SALARIO         int64
dtype: object

In [13]:
# Visualizando estatísticas descritivas do DataFrame
dfsalario.describe()

            SALARIO
count    106.000000
mean    6456.754717
std     3927.798234
min     2100.000000
25%     3100.000000
50%     6150.000000
75%     8950.000000
max    24000.000000

In [22]:
# Visualizando o valor médio da coluna "Salario" por departamento e cargo
dfsalario.groupby(['DEPARTAMENTO', 'CARGO'])['SALARIO'].mean()

DEPARTAMENTO      CARGO
Accounting        Accounting Manager                 12008.000000
                  Public Accountant                   8300.000000
Administration    Administration Assistant            4400.000000
Executive         Administration Vice President      17000.000000
                  President                          24000.000000
Finance           Accountant                          7920.000000
                  Finance Manager                    12008.000000
Human Resources   Human Resources Representative      6500.000000
IT                Programmer                          5760.000000
Marketing         Marketing Manager                  13000.000000
                  Marketing Representative            6000.000000
Public Relations  Public Relations Representative    10000.000000
Purchasing        Purchasing Clerk                    2780.000000
                  Purchasing Manager                 11000.000000
Sales             Sales Manager                      12200.000000
                  Sales Representative                8396.551724
Shipping          Shipping Clerk                      3215.000000
                  Stock Clerk                         2785.000000
                  Stock Manager                       7280.000000
Name: SALARIO, dtype: float64

In [23]:
# Visualizando o valor mediana da coluna "Salario" por departamento e cargo
dfsalario.groupby(['DEPARTAMENTO', 'CARGO'])['SALARIO'].median()

DEPARTAMENTO      CARGO
Accounting        Accounting Manager                 12008.0
                  Public Accountant                   8300.0
Administration    Administration Assistant            4400.0
Executive         Administration Vice President      17000.0
                  President                          24000.0
Finance           Accountant                          7800.0
                  Finance Manager                    12008.0
Human Resources   Human Resources Representative      6500.0
IT                Programmer                          4800.0
Marketing         Marketing Manager                  13000.0
                  Marketing Representative            6000.0
Public Relations  Public Relations Representative    10000.0
Purchasing        Purchasing Clerk                    2800.0
                  Purchasing Manager                 11000.0
Sales             Sales Manager                      12000.0
                  Sales Representative                8400.0
Shipping          Shipping Clerk                      3100.0
                  Stock Clerk                         2700.0
                  Stock Manager                       7900.0
Name: SALARIO, dtype: float64

In [20]:
# Visualizando o valor minimo da coluna "Salario" por departamento e cargo
dfsalario.groupby(['DEPARTAMENTO', 'CARGO'])['SALARIO'].min()

DEPARTAMENTO      CARGO
Accounting        Accounting Manager                 12008
                  Public Accountant                   8300
Administration    Administration Assistant            4400
Executive         Administration Vice President      17000
                  President                          24000
Finance           Accountant                          6900
                  Finance Manager                    12008
Human Resources   Human Resources Representative      6500
IT                Programmer                          4200
Marketing         Marketing Manager                  13000
                  Marketing Representative            6000
Public Relations  Public Relations Representative    10000
Purchasing        Purchasing Clerk                    2500
                  Purchasing Manager                 11000
Sales             Sales Manager                      10500
                  Sales Representative                6100
Shipping          Shipping Clerk                      2500
                  Stock Clerk                         2100
                  Stock Manager                       5800
Name: SALARIO, dtype: int64

In [21]:
# Visualizando o valor máximo da coluna "Salario" por departamento e cargo
dfsalario.groupby(['DEPARTAMENTO','CARGO'])['SALARIO'].max()

DEPARTAMENTO      CARGO
Accounting        Accounting Manager                 12008
                  Public Accountant                   8300
Administration    Administration Assistant            4400
Executive         Administration Vice President      17000
                  President                          24000
Finance           Accountant                          9000
                  Finance Manager                    12008
Human Resources   Human Resources Representative      6500
IT                Programmer                          9000
Marketing         Marketing Manager                  13000
                  Marketing Representative            6000
Public Relations  Public Relations Representative    10000
Purchasing        Purchasing Clerk                    3100
                  Purchasing Manager                 11000
Sales             Sales Manager                      14000
                  Sales Representative               11500
Shipping          Shipping Clerk                      4200
                  Stock Clerk                         3600
                  Stock Manager                       8200
Name: SALARIO, dtype: int64

Query 1 — Salário por Departamento e Cargo: